"""empty message

Revision ID: 635ea643867f
Revises: 
Create Date: 2019-12-15 17:56:20.851378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635ea643867f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('age', sa.String(length=80), nullable=True),
    sa.Column('height', sa.String(length=80), nullable=True),
    sa.Column('weight', sa.String(length=80), nullable=True),
    sa.Column('birthday', sa.String(length=80), nullable=True),
    sa.Column('astrological_sign', sa.String(length=80), nullable=True),
    sa.Column('bloodtype', sa.String(length=80), nullable=True),
    sa.Column('three_sizes', sa.String(length=80), nullable=True),
    sa.Column('handedness', sa.String(length=80), nullable=True),
    sa.Column('hobbies', sa.String(length=80), nullable=True),
    sa.Column('class_type', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('character', sa.Integer(), nullable=True),
    sa.Column('skill', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.String(length=80), nullable=False),
    sa.Column('stat_1', sa.Integer(), nullable=False),
    sa.Column('stat_2', sa.Integer(), nullable=False),
    sa.Column('stat_3', sa.Integer(), nullable=False),
    sa.Column('stat_4', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character'], ['Character.id'], ),
    sa.ForeignKeyConstraint(['skill'], ['Skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Card')
    op.drop_table('Skill')
    op.drop_table('Character')
    # ### end Alembic commands ###
