"""empty message

Revision ID: 6b0c7e3507d5
Revises: 
Create Date: 2019-12-13 22:00:20.398315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0c7e3507d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Character',
    sa.Column('id', sa.Integer().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('class_type', sa.String(length=120), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('bloodtype', sa.String(length=120), nullable=True),
    sa.Column('three_sizes', sa.String(length=120), nullable=True),
    sa.Column('handedness', sa.String(length=120), nullable=True),
    sa.Column('hobbies', sa.String(length=120), nullable=True),
    sa.Column('astrological_sign', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Skill',
    sa.Column('id', sa.Integer().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type_bonus', sa.String(length=120), nullable=True),
    sa.Column('stat_bonus', sa.String(length=120), nullable=True),
    sa.Column('multiplier', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Card',
    sa.Column('id', sa.Integer().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('character', sa.Integer(), nullable=True),
    sa.Column('skill', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.String(length=120), nullable=False),
    sa.Column('released', sa.DateTime(), nullable=False),
    sa.Column('stat_1', sa.Integer(), nullable=False),
    sa.Column('stat_2', sa.Integer(), nullable=False),
    sa.Column('stat_3', sa.Integer(), nullable=False),
    sa.Column('stat_4', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character'], ['Character.id'], ),
    sa.ForeignKeyConstraint(['skill'], ['Skill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Card')
    op.drop_table('Skill')
    op.drop_table('Character')
    # ### end Alembic commands ###
